global using AIDotNet.Document.Contract.Services;
global using AIDotNet.Document.Services.Services;
global using AIDotNet.Document.Contract.Models;
global using AIDotNet.Document.Services;
global using FreeSql;
global using Microsoft.KernelMemory;
global using Microsoft.KernelMemory.Configuration;
global using Microsoft.KernelMemory.FileSystem.DevTools;
global using Microsoft.KernelMemory.MemoryStorage.DevTools;